import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const DEMO_PREFIX = "[DEMO] ";

function demoLineItems() {
  return [
    {
      description: "Product sales",
      category: "Revenue",
      amount: 42800000,
    },
    {
      description: "Service revenue",
      category: "Revenue",
      amount: 6200000,
    },
    {
      description: "Cost of goods sold",
      category: "Expense",
      amount: -18600000,
    },
    {
      description: "Payroll and contractor costs",
      category: "Expense",
      amount: -9200000,
    },
    {
      description: "Rent and office operations",
      category: "Expense",
      amount: -3600000,
    },
    {
      description: "Marketing spend",
      category: "Expense",
      amount: -5400000,
    },
    {
      description: "Software subscriptions",
      category: "Expense",
      amount: -2100000,
    },
    {
      description: "Interest and bank charges",
      category: "Expense",
      amount: -900000,
    },
    {
      description: "Penalty for delayed vendor payment",
      category: "Risk",
      amount: -350000,
    },
    {
      description: "Bad debt write off",
      category: "Risk",
      amount: -650000,
    },
  ];
}

function demoTransactions() {
  return [
    {
      date: "2026-04-05",
      description: "Customer collection - enterprise order",
      amount: 7800000,
      direction: "credit",
    },
    {
      date: "2026-04-08",
      description: "Vendor payment - inventory",
      amount: -4200000,
      direction: "debit",
    },
    {
      date: "2026-04-18",
      description: "Payroll payout",
      amount: -2600000,
      direction: "debit",
    },
    {
      date: "2026-05-03",
      description: "Customer collection - retail channel",
      amount: 6200000,
      direction: "credit",
    },
    {
      date: "2026-05-11",
      description: "Marketing campaign payment",
      amount: -1800000,
      direction: "debit",
    },
    {
      date: "2026-06-02",
      description: "Customer collection - subscription invoices",
      amount: 7400000,
      direction: "credit",
    },
    {
      date: "2026-06-15",
      description: "Vendor payment - logistics",
      amount: -3100000,
      direction: "debit",
    },
  ];
}

function buildDemoDocuments(userId: string) {
  const now = new Date();

  return [
    {
      userId,
      fileName: `${DEMO_PREFIX}FY26 Financial Statement.pdf`,
      mimeType: "application/pdf",
      fileSize: 184000,
      category: "FINANCIAL_STATEMENT",
      status: "PROCESSED",
      reviewStatus: "APPROVED",
      reviewNote: "Demo approved financial statement for hackathon presentation.",
      uploadedAt: now,
      extractedAt: now,
      reviewedAt: now,
      content: Buffer.from("Demo financial statement generated by Aureli."),
      extractedData: {
        summary:
          "Demo financial statement for Aureli presentation. The business has strong revenue but expenses are higher than revenue, creating a loss and cash pressure.",
        documentDate: "2026-06-30",
        periodStart: "2026-04-01",
        periodEnd: "2026-06-30",
        currency: "INR",
        reportedUnit: "actual",
        scaleMultiplier: 1,
        unitDetectionEvidence: "Demo values are already in actual INR.",
        revenue: 49000000,
        totalRevenue: 49000000,
        sales: 42800000,
        expenses: 54100000,
        totalExpenses: 54100000,
        profit: -5100000,
        loss: 5100000,
        netIncome: -5100000,
        cash: 7800000,
        closingBalance: 7800000,
        assets: 31200000,
        liabilities: 17400000,
        equity: 13800000,
        totalAmount: -5100000,
        totalAmountLabel: "Net loss",
        lineItems: demoLineItems(),
      },
    },
    {
      userId,
      fileName: `${DEMO_PREFIX}Bank Statement Apr-Jun 2026.csv`,
      mimeType: "text/csv",
      fileSize: 42000,
      category: "BANK_STATEMENT",
      status: "PROCESSED",
      reviewStatus: "APPROVED",
      reviewNote: "Demo approved bank statement with cash inflow and outflow movement.",
      uploadedAt: now,
      extractedAt: now,
      reviewedAt: now,
      content: Buffer.from("date,description,amount,direction"),
      extractedData: {
        summary:
          "Demo bank statement showing customer collections, payroll, vendor payments, and marketing spend.",
        documentDate: "2026-06-30",
        periodStart: "2026-04-01",
        periodEnd: "2026-06-30",
        currency: "INR",
        cash: 7800000,
        closingBalance: 7800000,
        openingBalance: 9400000,
        totalAmount: 7800000,
        totalAmountLabel: "Closing balance",
        transactions: demoTransactions(),
        lineItems: [
          {
            description: "Total customer collections",
            category: "Inflow",
            amount: 21400000,
          },
          {
            description: "Total vendor payments",
            category: "Outflow",
            amount: -7300000,
          },
          {
            description: "Payroll payouts",
            category: "Outflow",
            amount: -2600000,
          },
          {
            description: "Marketing payments",
            category: "Outflow",
            amount: -1800000,
          },
        ],
      },
    },
    {
      userId,
      fileName: `${DEMO_PREFIX}Sales Invoices Summary.xlsx`,
      mimeType:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      fileSize: 76000,
      category: "SALES_INVOICE",
      status: "PROCESSED",
      reviewStatus: "APPROVED",
      reviewNote: "Demo sales invoices summary.",
      uploadedAt: now,
      extractedAt: now,
      reviewedAt: now,
      content: Buffer.from("Demo sales invoices summary"),
      extractedData: {
        summary:
          "Demo sales invoice summary with enterprise, retail, and subscription revenue.",
        documentDate: "2026-06-30",
        periodStart: "2026-04-01",
        periodEnd: "2026-06-30",
        currency: "INR",
        revenue: 49000000,
        totalRevenue: 49000000,
        sales: 49000000,
        totalAmount: 49000000,
        totalAmountLabel: "Invoice revenue",
        vendorOrCounterparty: "Multiple customers",
        lineItems: [
          {
            description: "Enterprise customer invoices",
            category: "Revenue",
            amount: 21400000,
          },
          {
            description: "Retail channel invoices",
            category: "Revenue",
            amount: 15100000,
          },
          {
            description: "Subscription invoices",
            category: "Revenue",
            amount: 12500000,
          },
        ],
      },
    },
    {
      userId,
      fileName: `${DEMO_PREFIX}Expense Bills Summary.xlsx`,
      mimeType:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      fileSize: 68000,
      category: "PURCHASE_INVOICE",
      status: "PROCESSED",
      reviewStatus: "APPROVED",
      reviewNote: "Demo purchase invoice summary.",
      uploadedAt: now,
      extractedAt: now,
      reviewedAt: now,
      content: Buffer.from("Demo purchase invoice summary"),
      extractedData: {
        summary:
          "Demo purchase invoice summary showing high recurring costs and risk items.",
        documentDate: "2026-06-30",
        periodStart: "2026-04-01",
        periodEnd: "2026-06-30",
        currency: "INR",
        expenses: 54100000,
        totalExpenses: 54100000,
        totalAmount: 54100000,
        totalAmountLabel: "Total expenses",
        vendorOrCounterparty: "Multiple vendors",
        lineItems: demoLineItems().filter((item) => item.amount < 0),
      },
    },
  ];
}

async function getSessionUserId() {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return session?.user?.id ?? null;
}

function revalidateDemoPaths() {
  [
    "/dashboard",
    "/documents",
    "/risk-score",
    "/cash-flow",
    "/forecast",
    "/decision-center",
    "/learning-center",
    "/anomaly-insights",
    "/document-completeness",
    "/chat",
    "/demo",
  ].forEach((path) => revalidatePath(path));
}

export async function GET() {
  try {
    const userId = await getSessionUserId();

    if (!userId) {
      return NextResponse.json(
        {
          error: "Unauthorized",
        },
        {
          status: 401,
        },
      );
    }

    const demoDocuments = await prisma.document.count({
      where: {
        userId,
        fileName: {
          startsWith: DEMO_PREFIX,
        },
      },
    });

    return NextResponse.json({
      demoDocuments,
      hasDemoData: demoDocuments > 0,
    });
  } catch (error) {
    console.error("Demo status error:", error);

    return NextResponse.json(
      {
        error: "Failed to load demo status.",
      },
      {
        status: 500,
      },
    );
  }
}

export async function POST(request: Request) {
  try {
    const userId = await getSessionUserId();

    if (!userId) {
      return NextResponse.json(
        {
          error: "Unauthorized",
        },
        {
          status: 401,
        },
      );
    }

    const body = await request.json().catch(() => ({}));
    const action = typeof body?.action === "string" ? body.action : "seed";

    await prisma.document.deleteMany({
      where: {
        userId,
        fileName: {
          startsWith: DEMO_PREFIX,
        },
      },
    });

    if (action === "reset") {
      revalidateDemoPaths();

      return NextResponse.json({
        success: true,
        action: "reset",
        message: "Demo data removed.",
      });
    }

    await prisma.business.upsert({
      where: {
        userId,
      },
      update: {
        name: "Aureli Demo Pvt Ltd",
        industry: "Retail and distribution",
        businessType: "SMB",
        financialYear: "2026-27",
        currency: "INR",
        country: "India",
      } as any,
      create: {
        userId,
        name: "Aureli Demo Pvt Ltd",
        industry: "Retail and distribution",
        businessType: "SMB",
        financialYear: "2026-27",
        currency: "INR",
        country: "India",
      } as any,
    });

    const documents = buildDemoDocuments(userId);

    for (const document of documents) {
      await prisma.document.create({
        data: document as any,
      });
    }

    revalidateDemoPaths();

    return NextResponse.json({
      success: true,
      action: "seed",
      message: "Demo business and approved demo documents created.",
      documentsCreated: documents.length,
    });
  } catch (error) {
    console.error("Demo seed error:", error);

    return NextResponse.json(
      {
        error: "Failed to create demo data.",
      },
      {
        status: 500,
      },
    );
  }
}