import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

type SampleDocument = {
  fileName: string;
  category:
    | "FINANCIAL_STATEMENT"
    | "BANK_STATEMENT"
    | "SALES_INVOICE"
    | "PURCHASE_INVOICE"
    | "PAYROLL"
    | "UTILITY_BILL";
  extractedData: Record<string, unknown>;
};

const DEMO_CONTENT = Buffer.from(
  "Demo sample document generated by Ledger for hackathon testing.",
);

const SAMPLE_DOCUMENTS: SampleDocument[] = [
  {
    fileName: "[Sample] FY 2024 Financial Statement.txt",
    category: "FINANCIAL_STATEMENT",
    extractedData: {
      summary:
        "Demo financial statement for a growing retail business. Revenue is healthy, expenses are controlled but still high, and the business is profitable with positive cash reserves.",
      documentDate: "2024-12-31",
      periodStart: "2024-01-01",
      periodEnd: "2024-12-31",
      currency: "INR",
      reportedUnit: "actual",
      scaleMultiplier: 1,
      unitDetectionEvidence: "Demo values are stored as actual INR amounts.",
      revenue: 4850000,
      totalRevenue: 4850000,
      sales: 4650000,
      expenses: 3620000,
      totalExpenses: 3620000,
      profit: 1230000,
      netIncome: 1230000,
      cash: 940000,
      closingBalance: 940000,
      assets: 3250000,
      liabilities: 1180000,
      equity: 2070000,
      lineItems: [
        {
          description: "Product sales",
          category: "Revenue",
          amount: 4650000,
        },
        {
          description: "Other operating income",
          category: "Revenue",
          amount: 200000,
        },
        {
          description: "Cost of goods sold",
          category: "Expense",
          amount: -1980000,
        },
        {
          description: "Marketing and sales expenses",
          category: "Expense",
          amount: -620000,
        },
        {
          description: "Rent and utilities",
          category: "Expense",
          amount: -420000,
        },
        {
          description: "Payroll",
          category: "Expense",
          amount: -600000,
        },
        {
          description: "Net profit",
          category: "Net Income",
          amount: 1230000,
        },
      ],
    },
  },
  {
    fileName: "[Sample] April 2024 Bank Statement.txt",
    category: "BANK_STATEMENT",
    extractedData: {
      summary:
        "Demo bank statement showing positive closing cash balance and regular inflows from customer payments.",
      documentDate: "2024-04-30",
      periodStart: "2024-04-01",
      periodEnd: "2024-04-30",
      currency: "INR",
      reportedUnit: "actual",
      scaleMultiplier: 1,
      unitDetectionEvidence: "Demo values are stored as actual INR amounts.",
      openingBalance: 720000,
      closingBalance: 940000,
      cash: 940000,
      revenue: 520000,
      expenses: 300000,
      profit: 220000,
      transactions: [
        {
          date: "2024-04-03",
          description: "Customer receipt",
          amount: 180000,
          direction: "credit",
        },
        {
          date: "2024-04-08",
          description: "Inventory purchase",
          amount: 95000,
          direction: "debit",
        },
        {
          date: "2024-04-15",
          description: "Customer receipt",
          amount: 210000,
          direction: "credit",
        },
        {
          date: "2024-04-20",
          description: "Rent payment",
          amount: 75000,
          direction: "debit",
        },
        {
          date: "2024-04-26",
          description: "Customer receipt",
          amount: 130000,
          direction: "credit",
        },
      ],
      lineItems: [
        {
          description: "Opening bank balance",
          category: "Asset",
          amount: 720000,
        },
        {
          description: "Cash inflows",
          category: "Revenue",
          amount: 520000,
        },
        {
          description: "Cash outflows",
          category: "Expense",
          amount: -300000,
        },
        {
          description: "Closing bank balance",
          category: "Asset",
          amount: 940000,
        },
      ],
    },
  },
  {
    fileName: "[Sample] Sales Invoice Batch.txt",
    category: "SALES_INVOICE",
    extractedData: {
      summary:
        "Demo sales invoice batch showing customer sales for April 2024.",
      documentDate: "2024-04-30",
      periodStart: "2024-04-01",
      periodEnd: "2024-04-30",
      currency: "INR",
      reportedUnit: "actual",
      scaleMultiplier: 1,
      totalAmount: 520000,
      totalAmountLabel: "Sales invoices",
      revenue: 520000,
      sales: 520000,
      vendorOrCounterparty: "Multiple customers",
      lineItems: [
        {
          description: "Customer invoice A",
          category: "Revenue",
          amount: 180000,
        },
        {
          description: "Customer invoice B",
          category: "Revenue",
          amount: 210000,
        },
        {
          description: "Customer invoice C",
          category: "Revenue",
          amount: 130000,
        },
      ],
    },
  },
  {
    fileName: "[Sample] Payroll Sheet.txt",
    category: "PAYROLL",
    extractedData: {
      summary:
        "Demo payroll sheet showing monthly salary cost for the business team.",
      documentDate: "2024-04-30",
      periodStart: "2024-04-01",
      periodEnd: "2024-04-30",
      currency: "INR",
      reportedUnit: "actual",
      scaleMultiplier: 1,
      totalAmount: 150000,
      totalAmountLabel: "Payroll expense",
      expenses: 150000,
      lineItems: [
        {
          description: "Operations team salary",
          category: "Payroll",
          amount: -85000,
        },
        {
          description: "Sales team salary",
          category: "Payroll",
          amount: -45000,
        },
        {
          description: "Part-time support",
          category: "Payroll",
          amount: -20000,
        },
      ],
    },
  },
];

async function ensureDemoBusiness(userId: string) {
  const existingBusiness = await prisma.business.findUnique({
    where: {
      userId,
    },
    select: {
      id: true,
    },
  });

  if (existingBusiness) {
    return;
  }

  await prisma.business.create({
    data: {
      userId,
      name: "Demo Retail Co.",
      industry: "Retail",
      businessType: "Startup",
      financialYear: "2024-25",
      currency: "INR",
      country: "India",
    },
  });
}

export async function POST() {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  if (!session?.user?.id) {
    return NextResponse.json(
      {
        error: "You must be signed in to create demo sample data.",
      },
      {
        status: 401,
      },
    );
  }

  const userId = session.user.id;
  const now = new Date();

  await ensureDemoBusiness(userId);

  await prisma.document.deleteMany({
    where: {
      userId,
      fileName: {
        startsWith: "[Sample]",
      },
    },
  });

  await prisma.document.createMany({
    data: SAMPLE_DOCUMENTS.map((sample) => ({
      userId,
      fileName: sample.fileName,
      mimeType: "text/plain",
      fileSize: DEMO_CONTENT.byteLength,
      category: sample.category,
      status: "PROCESSED",
      content: DEMO_CONTENT,
      extractedData: sample.extractedData,
      extractedAt: now,
      processingError: null,
      reviewStatus: "APPROVED",
      reviewedAt: now,
      reviewNote: "Auto-approved demo sample data.",
      uploadedAt: now,
    })),
  });

  revalidatePath("/dashboard");
  revalidatePath("/documents");
  revalidatePath("/chat");
  revalidatePath("/reports/cfo");
  revalidatePath("/business");

  return NextResponse.json({
    ok: true,
    message: "Demo sample data created successfully.",
    createdDocuments: SAMPLE_DOCUMENTS.length,
  });
}